apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - name: busybox-pod
    image: busybox
    command:  ["sleep","3600"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always