apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
spec:
  replicas: 1
  selector:
    name: redis-master
  template:
    metadata:
      labels:
        name: redis-master
    spec:
      contaniers:
      - name: master
        image:  kubeguide/redis-master
        ports:
        - contanierPort:  6379
      nodeSelector:
        zone: north


