apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-cloud-logging
  namespace:  kube-system
  labels:
    k8s-apps: fluentd-cloud-logging
spec:
  template:
    metadata:
      namespace:  kube-system
      labels:
        k8s-apps: fluentd-cloud-logging
    spec:
      containers:
      - name: fluentd-cloud-logging
        image:  kubernetes/fluentd-elasticsearch
        resources:
          limits:
            cpu:  100m
            memory: 200Mi
        env:
        - name: varlog
          mounthPath: /var/log
          readOnly: false
        - name: containers
          mounthPath: /var/lib/docker/containers
          readOnly: false
      volumes:
      - name: containers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log


